README.md
examples/node-app-mssql/connections.sync-db.json.example
src/config.ts

1. Refactor code for accessing database connections.
2. Update documentation.

Refactor code for accessing database connections.

---

README.md
examples/node-app-mssql/README.md
examples/node-app-mssql/package.json
examples/node-app-mssql/src/index.js
examples/node-app-mssql/yarn.lock

`yarn add @leapfrogtechnology/sync-db`

 Set published source for sync-db

---

README.md

Improvements:
- Use flat badges
- Add changelog and contributing sections
- Simplify Documentation; could still be simplified - **need suggestions**.

Improvements on the README Documentation

---

.travis.yml
README.md
package.json

Configure Travis CI for running tests

Configure Travis CI for running tests

---

src/Connection.ts
src/domain/DbConnectionInstance.ts
src/migrator.ts

* Support knex transactions in synchronize

Support knex transactions in synchronize

---

package.json
src/Connection.ts
src/domain/DbConnectionInstance.ts
src/migrator.ts
yarn.lock

* Downgrade knex version to 0.16.3
* Update types in synchronize

 Downgrade knex version to 0.16.3

---

package.json
yarn.lock

Upgrade TypeScript to 3.7.2

---

package.json
yarn.lock

Update dependencies to their latest versions:
- TypeScript
- TSlint

Update dependencies - typescript & tslint

---

src/util/fs.ts
test/fs.test.ts

Fix fs.exists() util ¯\\_(ツ)_/¯

Fix fs.exists() util ¯\_(ツ)_/¯

---

package.json
yarn.lock

Bump knex version to 0.20.11 (minimum).

Bump knex version to 0.20.11

---

.nycrc.json
.prettierignore
.travis.yml
examples/node-app-pg/src/index.js
examples/node-mssql-programmatic-use/src/index.js
package.json
src/domain/ConnectionConfig.ts
src/domain/RawBingingParams.ts
test/env.test.ts
test/tsconfig.json
tslint.json
yarn.lock

- Integrate prettier for formatting.
- Format files - few were inconsistent
- Check code formatting and lint on travis

Setup prettier and integrate format checking in the CI

---

.travis.yml
CHANGELOG.md
package.json

- Added `skip_cleanup` step in deployment stage to prevent cleaning up build artifacts
-  update sync-db package version to **1.0.0-beta.6**

Update package version => 1.0.0-beta.6

---

.travis.yml
CHANGELOG.md
package.json
release.sh

- Tag the release only once deployment is done

FIX - Tag package only after deploy stage

---

.travis.yml
release.sh

- Updated `release.sh` to auto generate changelog once the package is tagged

Update script to auto generate changelog

---

.travis.yml

- Install `github_changelog_generator`

FIX - Install changelog generator

---

CHANGELOG.md

- Update changelog as per changes made up to version **1.0.0-beta.8**
**FYI** This had to be done manaually as the deploy stage failed for last run in master due to which version change couldnot be tracked.

Update changelog manually

---

package.json

Move @istanbuljs/nyc-config-typescript to dev dependencies

Move @istanbuljs/nyc-config-typescript to dev dependencies

---

CHANGELOG.md
release.sh

- Update changelog up to version `1.0.0-beta.9`

Changelog for 1.0.0-beta.9 release 

---

package.json

- Update version to **1.0.0-beta.12**

Bump  version to 1.0.0-beta.12

---

src/api.ts
src/init.ts
src/migration/service/knexMigrator.ts
src/util/fs.ts
test/unit/util/fs.test.ts

- Fix error when migration field is removed from sync-db.yml

LPD-3225 : Fix error when migration field removed from sync-db.yml

---

package.json

- Upgrade sync-db to version 1.0.0
closes #138

Upgrade sync-db to version 1.0.0

---

package.json
src/commands/synchronize.ts
src/service/execution.ts
src/util/promise.ts

Verbose logging in case of synchronization failed for creating SQL and migration issue

Improve verbose logging
