leapfrogtechnology/sync-db

README.md
Add documentation of the following:
- Global Installation of sync-db
- Running sync-db through ngx
- Running sync-db when installed globally.
=> Add documentation for global installation

examples/node-app-mssql/package.json, examples/node-app-mssql/yarn.lock, package.json, yarn.lock
- Minimum requirement for knex is set to `0.19.5` as per the vulnerability reported here https://github.com/leapfrogtechnology/sync-db/network/alert/yarn.lock/knex/open.
Previous PR by @dependabot: https://github.com/leapfrogtechnology/sync-db/pull/22
=> Upgrade knex minimum version to 0.19.5

README.md
- Fix file name for `connections.sync-db.json` in README file
=> Fix file name mistake

package.json, src/Connection.ts, src/util/promise.ts, yarn.lock
- Use `PromiseLike` type to comply with knex return types which is incompatible with native `Promise` type
- Upgrade package: `codecov`
- Upgrade sub dependencies that were reported as vulnerable
=> Bump knex to version 0.20.4 and upgrade vulnerable packages

src/config.ts
The `connections.sync-db.json` generated using `--generate-connections` creates the connection with `port` as `string` while `sync-db` expect a `number`.
```bash
$ sync-db --generate-connections
```
Else it fails with the error:
`Error: An error occurred: TypeError: The "config.options.port" property must be of type number.`
For example,
Following `env` produces the connections below:
**`env`**
```
DB_CLIENT=mssql
DB_HOST=localhost
DB_PORT=1433
DB_USERNAME=user
DB_PASSWORD=Password@123
DB_NAME=db1
DB_ENCRYPTION=true
```
**Actual `connections.sync-db.json`**
```json
{
"connections": [
{
"client": "mssql",
"host": "localhost",
"port": "1433",
"user": "user",
"password": "Password@123",
"database": "db1",
"options": {
"encrypt": "true"
}
}
]
}
```
**Expected `connections.sync-db.json`** …
=> Generate connection with port as number when using --generate-connections CLI arg

src/config.ts
Port number 1433 is for mssql only; sync-db is vendor agnostic - at least it supports mssql and pg at the moment.
=> Avoid vendor specific defaults in the config

package.json, src/Connection.ts, src/config.ts, src/constants.ts, src/domain/KeyValuePair.ts, src/domain/SyncConfig.ts, src/migrator.ts, src/services/configInjection.ts, src/util/env.ts, src/util/types.ts, test/config.test.ts, test/configInjection.test.ts, test/env.test.ts, test/types.test.ts, tsconfig.json
- Ability to inject dynamic configurations into the scripts such that the scripts being run via sync-db can access them during the execution. 
- The lifetime of these configurations is limited to only when sync-db is running. And only the scripts directly triggered by `sync-db` can access them. Once they've finished running, the configurations are cleaned up.
- Tested and updated the sample project here :point_right:  https://github.com/leapfrogtechnology/sync-db/pull/37
Add configurations to be injected in the `sync-db.yml` file. It supports environment variable expansion too, so any confidential values / secrets could come through env vars as well.
```yml
hooks:
post_sync:
- scripts/setup.sql
injectedConfig:
vars:
create_admin: ${CREATE_ADMIN}
admin_email: 'admin@example.com' …
```
=> Config Injection - ability to inject dynamic configurations such that the running SQL transactions could access them

src/util/io.ts
- Add `io` utility to support standard IO operations like writing to `stdout` and `stderr`. This is a CLI application so all the outputs should go through these utilities to the stdout or stderr if error. 
- Logs are separate than this - logs are sent only when `DEBUG=` is provided, they are meant to go in the log service instead.
- The CLI output is for the user.
Streams in node will get unpredictable if we don't force between either a synchronous or asynchronous behavior. 
To be fully deterministic - they should be either 100% async or 100% sync - I chose async just to make things consistent with general IO.
=> Add new io utility for standard I/O operations

src/config.ts, src/constants.ts, test/config.test.ts
- Support resolving the connections from the environment variables if `connections.sync-db.json` does not exist.
- User don't always have to provide `connections.sync-db.json` now unless they want to or they have multiple connections.
- When this fallback option is chosen, if the environment variables required are not found an error is thrown just like what `--generate-connections` would have thrown.
- Add an ability to set connection `id` with environment variable `DB_ID`.
No need a workaround like these now when you want the connections to be generated:
```bash
$ sync-db --generate-connections && sync-db
```
Just this would do the same if you have your environment set
```bash
$ sync-db
```
=> Support resolving connections from the environment directly as a fallback option

src/api.ts
Fix ramda merge ¯\(ツ)/¯
- Ramda doesn't support `undefined` param
=> Fix ramda merge convert issue ¯\(ツ)/¯

.travis.yml, package.json
**BREAKING CHANGE**
- Drop node 8 support and require node 10.x as the minimum required version.
=> Drop Node 8.x support - minimum required version >= 10.x

.prettierrc, examples/node-app-mssql/.eslintrc, examples/node-app-mssql/docker-compose.yml, examples/node-app-mssql/src/migrations/20191124213800_create_tasks_table.js, examples/node-app-pg/docker-compose.yml, examples/node-app-pg/src/migrations/20191202053206_todos.js, examples/node-mssql-programmatic-use/.eslintrc, examples/node-mssql-programmatic-use/docker-compose.yml, examples/node-mssql-programmatic-use/src/migrations/20191124213800_create_task_table.js, package.json, yarn.lock
- Upgrade prettier to the latest version.
- Reconfigure few prettier due to new defaults
- Reformat whole codebase.
**Note:** Merge https://github.com/leapfrogtechnology/sync-db/pull/60 first. Requires node >= 10.
=> Upgrade prettier and reformat code

bin/run, package.json, src/@types/get-bin-path/index.d.ts, src/commands/synchronize.ts, src/index.ts, src/util/fs.ts, test/bootstrap.ts, test/commands/common.test.ts, test/commands/synchronize.test.ts, test/commands/util.ts, test/mocha.opts, test/tsconfig.json, test/util/fs.test.ts, tsconfig.json, yarn.lock
**BREAKING CHANGE**
- Requires node >= 10.x (Merge https://github.com/leapfrogtechnology/sync-db/pull/60 first)
- Need to transition to multi-commands CLI now as we're anticipating the migrations feature soon as per #51. This PR changes the CLI to allow that.
- You'll need to run `synchronize` command now to run the existing functionality:
```bash
$ sync-db synchronize
```
Previously, running just `sync-db` would have worked.
- Add CLI tests   
- **Preview**
**Why?**
This sets the ground for upcoming features we're going to have. We're going to need the following kinds of commands sooner:
```bash
- synchronize
- migrate:latest
- migrate:rollback
- migrate:list
- config:validate
- init
```
=> Transition to multi commands CLI

src/api.ts, src/commands/migrate-latest.ts, src/commands/migrate-list.ts, src/commands/migrate-rollback.ts, src/commands/prune.ts, src/commands/synchronize.ts, src/domain/operation/OperationParams.ts, src/util/list.ts, test/commands/synchronize.test.ts, test/util/list.test.ts
**The most awaited feature**
- Introduce the `--only` CLI option to filter connections for a single connection id.
* When provided, the command will be run for only that specific connection.
* By default (when not provided), the command will run for all connections same as before.
* The `only` option is also available for the Programmatic API usage.
- The option is supported in all of the commands: `synchronize`, `prune`, `migrate-latest`, `migrate-rollback`, `migrate-list`.
---
**Preview**
=> Ability to run all commands for a specific connection using a CLI option (--only)

examples/node-app-mssql/connections.sync-db.json.docker, examples/node-app-mssql/connections.sync-db.json.example, src/config.ts, src/domain/ConnectionConfig.ts, src/domain/ConnectionsFileSchema.ts, src/util/db.ts, test/util/config.test.ts
**BREAKING CHANGE**
- Connection config is made identical to the Knex's config. The only difference is we use only handful of those `client` and `connection` and we add `id` attribute for our internal purpose.
- Being consistent with Knex is important because we want to support the things Knex add out of the box, as much as possible.
- Programmatic API usage will break too - it expects type `ConnectionConfig | ConnectionConfig[]`.
**Checklist**
=> Make connections config consistent with Knex's config (breaking change)

assets/templates/migration/create_down.sql, assets/templates/migration/create_up.sql, package.json, src/commands/make.ts, src/migration/service/knexMigrator.ts, src/service/fileMaker.ts, src/util/fs.ts, src/util/string.ts, src/util/ts.ts, test/cli/commands/common.test.ts, test/cli/commands/make.test.ts, test/cli/commands/util.ts, test/unit/util/string.test.ts, test/unit/util/ts.test.ts
* Introduce `make` command to generate migration files.
* If it receives an argument in the form `create_<something>_table` then it will use the create table template for the file otherwise blank migration files are generated.
* In future it could support creating other DB objects like views, functions, etc with an optional option `--type` given
* Add ts utili function, few more tests
* Remove CLI tests from test coverage - it's not needed and it took very long time for the tests.
```
$ sync-db make create_test_table
```
```
$ sync-db make somethingelse
```
=> Introduce make command to generate migration files

src/commands/migrate-latest.ts, src/commands/migrate-list.ts, src/commands/migrate-rollback.ts, src/commands/prune.ts, src/commands/synchronize.ts, src/config.ts, src/constants.ts, src/domain/Configuration.ts
Resolves https://github.com/leapfrogtechnology/sync-db/issues/32
* Ability to use connection resolver via `--connection-resolver` option or `connectionResolver` configuration option in the `sync-db.yml` file. 
* Connection resolver is a javascript module that exposes a `resolve` function which resolves a list of database connection just in the same form as `connections.sync-db.json` file.
* Useful when you need to get the connections dynamically or from a separate service eg: vault, AWS secret manager, API etc. 
* Connection resolution process and order:
1. If connections file exists, use that to resolve connections.
2. If connection resolver is set via flag or configuration, use it.
3. If 1 & 2 are false, try resolving the connections from the environment. If not found fail with error.
* …
=> Support connection resolver

src/config.ts
Provide sync-db configuration object to the `resolve` function exposed by the connection resolver.
=> Provide configuration as an arg to the connection resolver's resolve function

.mocharc.json, package.json, test/mocha.opts, yarn.lock
* Upgrade `tslint` to `^6.1.3`
* Upgrade `kind-of`, `minimist` to non-vulnerable versions
* Upgrade `mocha` to `^7` which didn't have any vulnerable dependencies
Bonus: Remove `mocha.opts` (pending deprecation) in favor of `.mocharc.json`
=> Upgrade vulnerable packages

package.json, src/commands/migrate-latest.ts, src/commands/migrate-rollback.ts, src/commands/prune.ts, src/commands/synchronize.ts
Remove short character command for dry-run
```
➜  sync-db/examples/node-app-pg remove-dry-run-short-char ✓ yarn sync-db synchronize --help
yarn run v1.22.10
$ sync-db synchronize --help
Synchronize all the configured database connections.
USAGE
$ sync-db synchronize
OPTIONS
-f, --force                 Force synchronization.
--connection-resolver=PATH  Path to the connection resolver.
--dry-run                   Dry run synchronization.
--only=CONNECTION_ID        Filter only a single connection.
--skip-migration            Skip running migrations.
```
=> Remove short character (-f) command for dry-run

src/migration/service/migrator.ts, test/unit/migration/migrator.test.ts
**Issue:**
The problem was identified while replacing the knex migrator with sync-db migrator.
Reason: sync-db migrator removes the extension (`.ts, .js`) from filename while inserting in the migrations table but `Knex` migrator by default includes an extension. This corrupts the existing migrations because of the mismatched filename and migrations' table value.
| Knex Migrations Table | sync-db Migrations Table |
| -- | -- |
| 20170918131001_create_employees_table.ts | 20170918131001_create_employees_table |
**Solution**
Passing the full filename including an extension in migration object.
=> Fix migration issue by including file extension

release.sh, test/unit/service/execution.test.ts
Fix parallel strategy test case. 
https://stackoverflow.com/questions/44335770/node-mocha-chai-unit-tests-compare-array-of-objects-regardless-of-order
```
[
-  "Task A"
"Task C"
"Task D"
+  "Task A"
"Task B"
]
```
Fix release.sh script that was waiting for next task.
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```
=> Fix parallel strategy test case and release.sh script

README.md, package.json, release.sh, yarn.lock
Implement auto-update README.md about CLI usage and commands using `oclif-dev` library.
More detail:
```
➜  sync-db auto-update-doc ✓ yarn oclif-dev readme --help
yarn run v1.22.10
$ /Users/cham11ng/Source/sync-db/node_modules/.bin/oclif-dev readme --help
adds commands to README.md in current directory
USAGE
$ oclif-dev readme
OPTIONS
--dir=dir  (required) [default: docs] output directory for multi docs
--multi    create a different markdown page for each topic
DESCRIPTION
The readme must have any of the following tags inside of it for it to be replaced or else it will do nothing:
Customize the code URL prefix by setting oclif.repositoryPrefix in package.json.
```
=> Auto-update README.md about CLI usage and commands

package.json
* `ts-node` should be a dependency because running `TypeScript` migrations depends on it
=> Move ts-node to dependencies

examples/node-mssql-programmatic-use/connections.sync-db.json.example, package.json, src/migration/KnexMigrationSource.ts, src/service/execution.ts, src/util/promise.ts
Problem:
- `db.connection.transaction(async trx => { }` didn't rollback the transaction because no exception was thrown in SQL migration process. In case of migration and rollback `trx.migrate` and `trx.rollback` transaction rollback is handled internally.
- I've to remove the log from `getMigrationName` because it called more than a time which pollutes the console for a large number of migration files.
=> Throw an exception to rollback transaction if SQL migration fails

package.json, src/commands/make-publish.ts, src/commands/make.ts, src/commands/migrate-latest.ts, src/commands/migrate-list.ts, src/commands/migrate-rollback.ts, src/commands/prune.ts, src/commands/synchronize.ts, src/config.ts, test/cli/commands/make-publish.test.ts, test/cli/commands/make.test.ts, test/unit/util/config.test.ts
- Added `--config` flag in each command to provide custom config source for each command run
=> Ability to provide custom configuration with --config flag

src/commands/synchronize.ts
- Shows verbose error when corruption in migration files 
Fixes #124
=> Fix verbose error when corruption in migration files

src/api.ts
- The condition for `prepare` in synchonize api for loading migration wouldn't work correctly if skip-migration is set when dir exists 
- Remove redundant addition of dirExists check
=> Remove redundant existDir check

src/api.ts, src/commands/migrate-latest.ts
While running the migration commands, it kept failing. The reason was because the `prepare` function didn't know about the migration path. A quick fix has been applied to each function in `api.ts` which makes the prepare function aware of the migration path.
**Before:**
```
migrate-list
▸ db1 - Failed
Error: ENOENT: no such file or directory, scandir '/Users/saugat/Code/laudio/db/insights/migrations'
TransactionError: Can't rollback transaction. There is a request in progress.
Code: EREQINPROG
error Command failed with exit code 1.
---
migrate
▸ db1
[✓] Rollback - started
[✖] Rollback - failed (0s)
TransactionError: Can't rollback transaction. There is a request in progress.
Code: EREQINPROG
error Command failed with exit code 1.
```
**After:**
```
migrate
▸ db1
[✓] Synchronization - …
```
=> Send migration path before command execution

package.json, src/config.ts, src/service/sync.ts, src/util/promise.ts
**Problem**
While syncing database objects like views, and functions with sync-db, if there were any problems with the query files, then sync-db would not throw any errors but rather complete successfully and the database objects would not be created. That would lead us to believe that the operation was successful because the problems won't be revealed to us.
**Change**
This change fixes the problem by throwing errors if there were any errors in the synchronization scripts.
**Before, even in the case of problems**
**After**
=> Fail synchronization if any error occurs while running sql scripts

README.md, package.json, src/constants.ts, src/domain/SqlCode.ts, src/service/sqlRunner.ts, src/util/promise.ts, test/unit/migration/migrator.test.ts
**Problem**
The only way we have right now to remove an already synced database is to first remove the view manually, and then remove it from the config file and remove the actual file. 
**Change**
With this change, we can just append `.dropped` to any database object in the config file, and then sync-db will only drop the view/function/proc and not synchronize (up) it. We can remove that object from the config file immediately after synchronization or after some point in time.
=> Skip synchronization of a database object if .dropped is appended on its name

README.md, examples/node-app-mssql-ts/src/sql/view/utils/vw_user_emails.sql, examples/node-app-mssql-ts/sync-db.yml, examples/node-app-mssql/src/sql/view/utils/vw_user_emails.sql, examples/node-app-mssql/sync-db.yml, examples/node-app-pg-ts/src/sql/view/utils/vw_current_queries.sql, examples/node-app-pg-ts/sync-db.yml, examples/node-app-pg/src/sql/view/utils/vw_current_queries.sql, examples/node-app-pg/sync-db.yml, examples/node-mssql-programmatic-use/src/sql/view/utils/vw_principals.sql, examples/node-mssql-programmatic-use/sync-db.yml, package.json, src/constants.ts, src/service/sqlRunner.ts
- Rename the occurrences of `.dropped` to `.drop`
- Update examples to include the usage of `.drop`
- Update version
=> Rename `.dropped` to `.drop` & update examples

src/commands/migrate-list.ts
- The result of running the migration list returns data as above now. Previously, it used to be just the array of names
- I am not sure about the cause, but don't see any related changes in recent commits
Fixes https://github.com/leapfrogtechnology/sync-db/issues/204
=> Fix the type displayed instead of migration name with migrate-list

package.json, src/api.ts, src/commands/migrate-list.ts, src/util/fs.ts
- Just to avoid confusion, sometimes the migration directory does not need to exist for sync db to run. In those cases, we don't need to log an error
=> Remove error log when dir does not exist (v2.0.1 Release)

README.md, package.json, src/api.ts
- For multiple connection provided to sync-db, it was difficult to filter a subset of connection for which we require to synchronize the migrations. `--only` flag supported only a single connectionId which is a bit hectic
- Update `--only` to support multiple `,` separated connection identifiers
- Any unwanted connection ids also get filtered if provided
```
{
"connections": [
{
"id": "db1",
"client": "mssql",
"connection": {
"host": "mssql",
"port": 1433,
"user": "sa",
"database": "tempdb",
"password": "Secret@123"
}
},
{
"id": "db2",
"client": "mssql",
"connection": {
"host": "mssql",
"port": 1433,
"user": "sa",
"database": "tempdb1",
"password": "Secret@123"
}
},
{
"id": "db3",
"client": "mssql",
"connection": {
"host": "mssql",
"port": 1433,
"user": "sa",
"database": "tempdb2", …
```
=> Update --only flag to support multiple connection filter

.github/workflows/build-publish.yml, README.md, package.json, src/commands/migrate-latest.ts, src/commands/migrate-list.ts, src/commands/migrate-rollback.ts, src/commands/prune.ts, src/commands/synchronize.ts
- Update docs to include multiple connection ids
- Add github token in env for release to make sure tags are pushed and release does happen
- Bump `package.json` version for new patch release
=> Update docs to reflect connection id filtering

src/config.ts, src/constants.ts
closes #225
- Update base path to be relative to sync-db config file location
- Update name extraction condition
- Update default value for base path
- directory structure
1. CMD yarn sync-db migrate-list --config=./src/sync-db.yml
2. CMD yarn sync-db migrate-rollback --config=./src/sync-db.yml
3. CMD yarn sync-db migrate-latest --config=$(pwd)/src/sync-db.yml
4. CMD yarn sync-db synchronize --config=$(pwd)/src/sync-db.yml
5. CMD yarn sync-db make test_update_example --config=$(pwd)/src/sync-db.yml
- directory structure 2
1. CMD yarn sync-db migrate-list --config=./sync-db.yml
2. CMD yarn sync-db migrate-rollback --config=./sync-db.yml
3. CMD yarn sync-db migrate-latest --config=$(pwd)/sync-db.yml
4. CMD yarn sync-db synchronize --config=$(pwd)/sync-db.yml
=> Use relative base path respective to config file

.github/workflows/build-publish.yml, package.json, yarn.lock
- Update `build-publish` workflow to use codecov upload action instead of codecov package
- Remove deprecated `codecov` package
- New version: `2.2.0` to include changes in #237
=> Update build workflow to include codecov upload step
